services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: salve-food
      POSTGRES_DB: salve-food
      POSTGRES_USER: usuario
    ports:
      - 5434:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts/entrypointtwo.sh:/docker-entrypoint-initdb.d/entrypointtwo.sh
    networks:
      - juntatudo
    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/entrypointtwo.sh"]
    command: ["postgres"]
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    ports:
      - "9001:9001"
      - "9091:9091"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_VOLUMES: "/data"
      MINIO_NOTIFY_POSTGRES_ENABLE: "on"
      MINIO_NOTIFY_POSTGRES_CONNECTION_STRING: "host=db user=usuario password=salve-food dbname=salve-food sslmode=disable"
      MINIO_NOTIFY_POSTGRES_TABLE: "minio"
      MINIO_NOTIFY_POSTGRES_FORMAT: "namespace"
    volumes:
      - ./minio-data:/data
    command: server --console-address "0.0.0.0:9091" /data --address 0.0.0.0:9001
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      test: ["CMD", "curl", "-f"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - db
    networks:
      - juntatudo
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    restart: always
    hostname: keycloak.quiz.local
    domainname: quiz.local
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: senha1234
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/salve-food
      KC_DB_USERNAME: usuario
      KC_DB_PASSWORD: salve-food
    depends_on:
      - db
    command: ["start-dev","--http-host=0.0.0.0"]
    volumes:
      - ./keycloak-data:/opt/jboss/keycloak/standalone/data
      - ./keycloak-themes:/opt/jboss/keycloak/themes
      - ./keycloak-realm:/opt/jboss/keycloak/standalone/configuration/keycloak-realm.json
    networks:
      - juntatudo
  api:
    build: ./
    restart: always
    environment:
      SPRING_APPLICATION_NAME: salve-food-api
      SERVER_PORT: 8080
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/salve-food
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: salve-food
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
      LOGGING_LEVEL_COM_SALVEFOOD: DEBUG
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      LOCAL_IP: ${LOCAL_IP}
      MINIO_URL: http://${LOCAL_IP}:9001
      MINIO_ACCESS_KEY: RoNHWxprGCgAVlnhOGbi
      MINIO_SECRET_KEY: 4f8FWguq4ZkWphPIGCATdsR7uFUmwuGhi2HzL4at
      KEYCLOAK_ISSUER_URI: http://${LOCAL_IP}:9080/realms/salve
      KEYCLOAK_JWK_SET_URI: http://${LOCAL_IP}:9080/realms/salve/protocol/openid-connect/certs
      KEYCLOAK_LOGOUT_URI: http://${LOCAL_IP}:9080/realms/salve/protocol/openid-connect/logout
      KEYCLOAK_ROLES_URI: http://${LOCAL_IP}:9080/admin/realms/salve/roles
      KEYCLOAK_ADMIN_USERNAME: adminsalve
      KEYCLOAK_ADMIN_PASSWORD: adminsalve
      KEYCLOAK_REALM_URI: http://${LOCAL_IP}:9080/realms/master
      KEYCLOAK_CREATE_USER_URI: http://${LOCAL_IP}:9080/admin/realms/salve/users
      APPLICATION_URL: http://${LOCAL_IP}:5173,http://${LOCAL_IP}:8080,http://${LOCAL_IP}:9080,ws://${LOCAL_IP}:8080
    ports:
      - 8080:8080
    depends_on:
      - db
      - minio
    networks:
      - juntatudo
  
networks:
  juntatudo:
    driver: bridge
