version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: salve-food
      POSTGRES_DB: salve-food
      POSTGRES_USER: usuario
    ports:
      - 5434:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - juntatudo
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    ports:
      - "9001:9001"
      - "9091:9091"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_VOLUMES: "/data"
      MINIO_NOTIFY_POSTGRES_ENABLE: "on"
      MINIO_NOTIFY_POSTGRES_CONNECTION_STRING: "host=db user=usuario password=salve-food dbname=salve-food sslmode=disable"
      MINIO_NOTIFY_POSTGRES_TABLE: "minio"
      MINIO_NOTIFY_POSTGRES_FORMAT: "namespace"
    volumes:
      - ./minio-data:/data
    command: server --console-address "0.0.0.0:9091" /data --address 0.0.0.0:9001
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      test: ["CMD", "curl", "-f"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - db
    networks:
      - juntatudo

  api:
    build: ./
    restart: always
    environment:
      SPRING_APPLICATION_NAME: salve-food-api
      SERVER_PORT: 8080
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/salve-food
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: salve-food
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_TEMP_USE_JDBC_METADATA_DEFAULTS: "false"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQL9Dialect
      SPRING_JPA_GENERATE_DDL: "true"
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      MINIO_URL: http://minio:9001
      MINIO_ACCESS_KEY: 9AmF1hfTKjWvnXNQntBW
      MINIO_SECRET_KEY: LRou1qQPMGBvHavUg59WL21PYg38WGEdEmF1CSUP
    ports:
      - 8080:8080
    depends_on:
      - db
      - minio
    networks:
      - juntatudo
  
networks:
  juntatudo:
    driver: bridge
